#!/bin/bash

# http://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# python -m py_compile caesar.py
# cd __pycache__/
# mv caesar.cpython-36.pyc ../caesar.pyc
python3 "$DIR/caesar.pyc" "$@"
