#!/bin/bash

# http://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# python -m py_compile cash.py
# cd __pycache__/
# mv cash.cpython-36.pyc ../cash.pyc
python3 "$DIR/cash.pyc" "$@"
