#!/bin/bash

# http://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# python -m py_compile vigenere.py
# cd __pycache__/
# mv vigenere.cpython-36.pyc ../vigenere.pyc
python3 "$DIR/vigenere.pyc" "$@"
